version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aviacao-app
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
    networks:
      - aviacao-network
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: aviacao-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../data/aviacao.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../data/populate.sql:/docker-entrypoint-initdb.d/02-populate.sql
      - ../data/index.sql:/docker-entrypoint-initdb.d/03-index.sql
      - ../data/view.sql:/docker-entrypoint-initdb.d/04-view.sql
      - ../data/olap.sql:/docker-entrypoint-initdb.d/05-olap.sql
    networks:
      - aviacao-network
    restart: unless-stopped

networks:
  aviacao-network:
    driver: bridge

volumes:
  postgres-data:
